### PR TITLE
Add sinatra version, a few more scripts, Dockerfile, update README

### PR DESCRIPTION
**Pull request by zxjinn**
Hey! I forked your repo over a year ago and have been using this Sinatra app successfully for the entire time. I'm just now getting around to making a pull request to push that functionality upstream. I'm using it with a VSX-1124k btw.

The only backwards incompatible change I believe is that I renamed `scripts/toggle` → `scripts/toggle_power` because I added a `toggle_mute` script and didn't want to cause confusion with what toggle meant.

I've added a bunch of things to the README, including how to use the Sinatra app, let me know what you think!

### CODE REVIEW

**Comment by zxjinn** [comment]
FYI besides the Docker stuff, I also added a [travelling ruby](http://phusion.github.io/traveling-ruby/) config to my fork if you are interested in adding that I can make another PR with that in it. :smile:

**Comment by grf** [comment]
On Sat, Feb 6, 2016 at 11:33 PM, Kelvin Jasperson notifications@github.com
wrote:

> Hey! I forked your repo over a year ago and have been using this Sinatra
> app successfully for the entire time. I'm just now getting around to making
> a pull request to push that functionality upstream. I'm using it with a
> VSX-1124k btw.
> 
> The only backwards incompatible change I believe is that I renamed
> scripts/toggle → scripts/toggle_power because I added a toggle_mute
> script and didn't want to cause confusion with what toggle meant.
> 
> I've added a bunch of things to the README, including how to use the
> 
> ## Sinatra app, let me know what you think!

Kelvin, so cool!

I've been thinking about adding a sinatra interface,  nice to see.   I
don't know too much about docker and nothing at all about traveling ruby,
I'll check it out.

The vsx-1021 actually has two ports it listens to, 23 and 8102 - the
current master branch code tries both in turn.

Does the vsx-1124 use the 8102 port?  (you could 'telnet vsx.example.com
8102'   and see if you get a connection).

I'm very glad you found it useful.   I'll be in touch,  but it may well be
a while - I'm wrapped around the axle just now with work- and home- life)

Very cool.

-Randy Fischer

**Comment by zxjinn** [comment]
I used traveling ruby for 6-9 months or so when I got tired of managing RVM on the server this was running on, it makes it easy to package up the app and just run it instead of messing with Ruby, and Gems, and etc. I'm no longer using it as I've migrated to Docker, but if you think you'd be interested in using it (or anyone else that might use this?) I'm more than happy to submit that pr. This one was big enough so I left it out.

Looks like both ports are open- 23 and 8102 on mine. Seems when I forked your repo it was late September of 2014 and that code had both ports in it, which is strange because I never realized that was before. Either way, it's been working beautifully with OpenRemote to connect to my Sinatra app.

Good luck with your work and home life :smile: No worries about the time, I've been forked for 18 months now and I've been doin' just fine!

**Comment by grf** [comment]
On Sun, Feb 7, 2016 at 12:47 AM, Kelvin Jasperson notifications@github.com
wrote:

> ...it's been working beautifully with OpenRemote to connect to my Sinatra
> app.

Is this the OpenRemote you're talking about?  -
http://www.openremote.org/display/HOME/OpenRemote

**Comment by zxjinn** [comment]
Precisely. [Attached](https://cloud.githubusercontent.com/assets/1184723/12876283/2869064c-cdbc-11e5-8b54-9bd49bc367d4.png) is my juvenile openremote interface from my phone I've been using, it connects to my TV with [my project](https://github.com/zxjinn/sharp_aquos_control) and the receiver with this project.

I've been pretty happy with OpenRemote so far

**Comment by zxjinn** [comment]
Hey @grf! I was looking through my open pull requests and saw this was still open. Any problems with merging it, or have you had time to test? Thanks!

**Comment by grf** [comment]
On Wed, Aug 24, 2016 at 6:39 PM, Kelvin Jasperson notifications@github.com
wrote:

> Hey @grf https://github.com/grf! I was looking through my open pull
> requests and saw this was still open. Any problems with merging it, or have
> you had time to test? Thanks!

Kevin, thanks for the ping - I've been in hospital for a while, I haven't
forgotten you!

I'm afraid I've been wrapped around the axle at work as I try to to get
back up to speed (I'm 59 years old, it takes a while to recover at this age
- I don't spring back like a puppy anymore), but I realize I've let you
  down here.... I've put your project on my short list.  I'm not yet sure how
  I'll proceed - I like very much what I've seen of your code.

I'll be in touch before too long - my apologies.

Thanks so much - I really appreciate your work.

-Randy Fischer

**Pull request closed without merging**
